server:
  port: 8036
spring:
  application:
    name: springcloud-sentienl
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080